site_name: Journal Club
theme:
    name: material
    language: en
    palette:
      scheme: default
      primary: indigo
      accent: White
    font:
      text: Arial
      color: White
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - content.code.annotate
      - content.tabs.link

nav:
  - About: /JournalClub/index.html
  - Articles: 
    - Review
  
  - Code Examples: CodeExample
  
  - Dictionary: Dictionary
    
  - Other materials: MyDocuments/index.md



markdown_extensions:
  - def_list

  - attr_list
  
  - md_in_html
  
  - pymdownx.inlinehilite
  
  - pymdownx.snippets
  
  - pymdownx.superfences
  
  - footnotes
  
  - tables
  
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - mkdocs-jupyter
  - glightbox

extra:
  analytics:
    provider: google
    property: G-E8M7KJ8BVB